micronaut:
  application:
    name: desafioPix
  server:
    port: 8081

#;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
datasources:
  default:
    url: ${JDBC_URL:`jdbc:h2:mem:pix`}
    username: ${JDBC_USER:sa}
    password: ${JDBC_PASSWORD:""}
    driverClassName: ${JDBC_DRIVER:org.h2.Driver}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true

itau:
  erp:
    server-url: 'http://localhost:9091'

bcb:
  pix:
    server-url: 'http://localhost:8082'